### ISSUE TITLE
with environment

### ISSUE THREAD

**Issue by ZekYi** [jwwthu/DL4Internet#1]
Could you send python environment in this？

**Comment by jwwthu** [comment]
Please check any notebook. I have imported all the required packages and printed the versions at the begining.

**Comment by ZekYi** [comment]
> Please check any notebook. I have imported all the required packages and printed the versions at the begining.

Greate!

**Comment by ZekYi** [comment]
> Please check any notebook. I have imported all the required packages and printed the versions at the begining.

Please reply to the version number with sktime，thanks！

**Comment by jwwthu** [comment]
I am sorry but I do not know the sktime version. I use tsai in my code. When I install tsai, the dependencies (including sktime I think) are installed automatically. I hope this situation helps to answer your question.

**Comment by ZekYi** [comment]
> I am sorry but I do not know the sktime version. I use tsai in my code. When I install tsai, the dependencies (including sktime I think) are installed automatically. I hope this situation helps to answer your question.

I tring sktime==0.6.1 is OK
